### ISSUE TITLE
Error predicting forest images.

### ISSUE THREAD

**Issue by sampath017** [MadalinTat/Practical-Deep-Learning-for-Coders#1]
for 00 chapter when used forest.jpg image to predict weather it's a bird or not the model predicts it a bird with 1.0 probability.

output:
`This is a: bird.
Probability it's a forest: 1.0000`

I need some help figuring this out.

**Comment by MadalinTat** [comment]
The solution is to change the string from "forest" to "bird" -> "Probability it is a bird:".
(I think that's how it was in the original notebook too)

**Comment by sampath017** [comment]
learner.predict() function returns the string and probability so when I give a forest image to this model i should get forest as answer right.

```
is_forest, _, probs = learner.predict(data_folder / "forest.jpg")
print(f"This is a: {is_forest}.")
print(f"Probability it's a forest: {probs[0]:.4f}")
```

I will double check the architecture again.

**Comment by sampath017** [comment]
The issue is the birds have some colors, so the model is much more biased to birds. I encourage to check these comments for some insights.
https://www.kaggle.com/code/jhoward/is-it-a-bird-creating-a-model-from-your-own-data/comments#1923693

I hope this resolves the issue.
